apiVersion: v1
kind: Service
metadata:
  labels:
    app: sec-nac
  name: sec-nac
  namespace: sec-nac
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sec-nac
  type: LoadBalancer
  loadBalancerIP: 192.168.10.151
