name: Test and Deployment to K3s cluster

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: 	ubuntu-latest
#    strategy:
#      matrix:
#        r-version: [3.6]

    steps:
      - uses: actions/checkout@v2
        
#      - name: Install dependencies
#        run: |
#          install.packages(c("remotes", "rcmdcheck"))
#          remotes::install_deps(dependencies = TRUE)
#        shell: Rscript {0}
#      - name: Test WebApp
#        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
#        shell: Rscript {0}
     
      - name: Build and Push Container 
        id: test
        uses: ryanjfrizzell/action-bpd@master
        with:
          docker_username: ${{ secrets.dockerhub_username }}
          docker_password: ${{ secrets.dockerhub_password }}
          docker_image_tag: 'auto-latest'
          docker_registry: 'drumsergio/secciones-nacionalidades'
          dockerhub: 'true'
          dockerfile: 'Dockerfile'
      - name: Get the output
        run: |
          echo "imageinfo was ${{ steps.test.outputs.imageinfo }}"
          
      - name: Deploy to Kubernetes
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.kubeconfig_data }}
          KUBECTL_VERSION: "1.18"
        with:
          args: set image --record deployment/sec-nac container=${{ github.repository }}:auto-latest

          


